version: "3.3"

services:
  onvif-proxy:
    image: onvif-proxy
    container_name: onvif-proxy
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 80 --conf_path "/flask-app/confs/conf.json" --cam_num 0'
    restart: always
    ports:
      - "80:80"

  onvif-proxy1:
    image: onvif-proxy
    container_name: onvif-proxy1
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 8001 --conf_path "/flask-app/confs/conf.json" --cam_num 1'
    restart: always
    ports:
      - "8001:8001"
      
  onvif-proxy2:
    image: onvif-proxy
    container_name: onvif-proxy2
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 8002 --conf_path "/flask-app/confs/conf.json" --cam_num 2'
    restart: always
    ports:
      - "8002:8002"
      
  onvif-proxy3:
    image: onvif-proxy
    container_name: onvif-proxy3
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 8003 --conf_path "/flask-app/confs/conf.json" --cam_num 3'
    restart: always
    ports:
      - "8003:8003"
      
  onvif-proxy4:
    image: onvif-proxy
    container_name: onvif-proxy4
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 8004 --conf_path "/flask-app/confs/conf.json" --cam_num 4'
    restart: always
    ports:
      - "8004:8004"
      
  onvif-proxy5:
    image: onvif-proxy
    container_name: onvif-proxy5
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 8005 --conf_path "/flask-app/confs/conf.json" --cam_num 5'
    restart: always
    ports:
      - "8005:8005"
      
  onvif-proxy6:
    image: onvif-proxy
    container_name: onvif-proxy6
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 8006 --conf_path "/flask-app/confs/conf.json" --cam_num 6'
    restart: always
    ports:
      - "8006:8006"
      
  onvif-proxy7:
    image: onvif-proxy
    container_name: onvif-proxy7
    command: 'onvif/bin/python main.py --ip 0.0.0.0 --port 8007 --conf_path "/flask-app/confs/conf.json" --cam_num 7'
    restart: always
    ports:
      - "8007:8007"